section 'getting-started', "Rhodes API Reference" do
  topic 'home',                 'Home'
  topic 'alert-api',             'Alert'
  topic 'asynchttp-api',             'AsyncHttp'
  topic 'barcode-api',             'Barcode'
  topic 'bluetoothmanager-api',             'BluetoothManager'
  topic 'bluetoothsession-api',             'BluetoothSession'
  topic 'camera-api',             'Camera'
  topic 'file-api',             'File'
  topic 'mapview-api',             'MapView'
  topic 'rhoerror-api',             'RhoError'
  topic 'rholog-api',             'RhoLog'
  topic 'rhom-api',             'Rhom'
  topic 'rhomsource-api',             'RhomSource'
  topic 'rhoutils-api',             'RhoUtils'
  topic 'ringtonemanager-api',             'RingtoneManager'
  topic 'signaturetool-api',             'SignatureTool'
  topic 'syncengine-api',             'SyncEngine'
  topic 'timer-api',             'Timer'
end