section 'getting-started', "Rhodes API Reference" do
  topic 'home',                 'Home'
  topic 'alert-api',             'Alert API'
  topic 'asynchttp-api',             'AsyncHttp API'
  topic 'barcode-api',             'Barcode API'
  topic 'bluetoothmanager-api',             'BluetoothManager API'
  topic 'bluetoothsession-api',             'BluetoothSession API'
  topic 'camera-api',             'Camera API'
  topic 'file-api',             'File API'
  topic 'mapview-api',             'MapView API'
  topic 'rhoerror-api',             'RhoError API'
  topic 'rholog-api',             'RhoLog API'
  topic 'rhom-api',             'Rhom API'
  topic 'rhomsource-api',             'RhomSource API'
  topic 'rhoutils-api',             'RhoUtils API'
  topic 'ringtonemanager-api',             'RingtoneManager API'
  topic 'signaturetool-api',             'SignatureTool API'
  topic 'syncengine-api',             'SyncEngine API'
  topic 'timer-api',             'Timer API'
end